#ifndef UDEVNOTIFIER_GLOBAL_H
#define UDEVNOTIFIER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UDEVNOTIFIER_LIBRARY)
#  define UDEVNOTIFIERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UDEVNOTIFIERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UDEVNOTIFIER_GLOBAL_H
